### ISSUE TITLE
Doesn't update if callback changed

### ISSUE THREAD

**Issue by aendrew** [Hermanya/use-interval#17]
Currently if you have something like

```js
const useMyHook = (url) => {
  const [data, setData] = useState(null);
  useInterval(() => {
    (async () => {
       setData(await (await fetch(url)).json());
    })();
  }, 1000, true);
  return data;
};
```
...The `useInterval` callback doesn't seem to grab a new URL if you change the URL provided to the hook.

**Comment by Hermanya** [comment]
In your case the callback does not change 😬
Try using useCallback, add url as a dependency there, and pass the resulting callback into useInterval. It should work as expected.

**Comment by aendrew** [comment]
@Hermanya I did try `useCallback` and it seemed to not have any effect. I ended up writing forking the hook locally and then adding a separate dependency array to the hook that causes the two `useEffect` hooks to re-evaluate if anything changes, but it seems like this is unnecessary:
```js
// Modified from https://github.com/Hermanya/use-interval/blob/master/src/index.tsx
export function useInterval(callback, delay, immediate, deps = []) {
  const savedCallback = useRef(noop);
  // Remember the latest callback.
  useEffect(() => {
    savedCallback.current = callback;
  }, [callback, ...deps]);

  // Execute callback if immediate is set.
  useEffect(() => {
    if (!immediate) return;
    if (delay === null || delay === false) return;
    savedCallback.current();
  }, [immediate, ...deps]);

  // Set up the interval.
  useEffect(() => {
    if (delay === null || delay === false) return undefined;
    const tick = () => savedCallback.current();
    const id = setInterval(tick, delay);
    return () => clearInterval(id);
  }, [delay]);
}
```

Maybe it's because the `immediate` effect wasn't being triggered when the callback updated?
