### ISSUE TITLE
Immediate arg doesn't work if delay is null on mount.

### ISSUE THREAD

**Issue by phaux** [Hermanya/use-interval#27]
I was expecting that the callback would run immediately not only on mount, but also on every resume (when delay changes from null to any number).

If that might be not desired then maybe add another option for that:

```js
useInterval(cb, delay, { runOnMount: true, runOnResume: true })
useInterval(cb, delay, true) // same as { runOnMount: true, runOnResume: false }
useInterval(cb, delay) // same as { runOnMount: false, runOnResume: false }
```

I can send a PR.

**Comment by Hermanya** [comment]
That's an interesting idea, PR definitely welcome

**Comment by phaux** [comment]
BTW I just found a workaround: 

```js
useInterval(
  playSound,
  isPlaying ? 500 : null,
  isPlaying
) 
```

If you change delay from null to any number and immediate from false to true at the same time then it works as expected.
