### ISSUE TITLE
Support `false` for delay argument

### ISSUE THREAD

**Issue by G-Rath** [Hermanya/use-interval#4]
While not in the original article, I think it would be useful to support `false` as well as `null`, as it lets you do:

```
  useInterval(() => {
    if (currentStep >= steps.length - 1) {
      setIsPlaying(false);

      return;
    }
    setCurrentStep(step => step + 1);
  }, isPlaying && 200);
```

In TypeScript you'd change `delay` to be type `number | null | false`, and then just do `delay === null || delay === false`.

**Comment by Hermanya** [comment]
That's an interesting idea, I suppose there is no reason not to support other falsy values 😄
PR welcome
